In [8]:
import numpy as np
import time

In [9]:
R = np.random.randint(10, size= (5,5))
R

array([[0, 5, 0, 7, 6],
       [8, 4, 6, 8, 1],
       [0, 4, 5, 0, 4],
       [7, 3, 4, 2, 4],
       [9, 6, 5, 8, 8]])

In [10]:
type(R)

numpy.ndarray

In [12]:
R[0] # PROTI GRAMMI

array([0, 5, 0, 7, 6])

In [11]:
R[:, 0]

array([0, 8, 0, 7, 9])

In [13]:
R[:, 3]

array([7, 8, 0, 2, 8])

In [14]:
R[0,0]

0

In [15]:
R[-1,-1]

8

In [16]:
R[-1]

array([9, 6, 5, 8, 8])

In [18]:
R[:, :-1]

array([[0, 5, 0, 7],
       [8, 4, 6, 8],
       [0, 4, 5, 0],
       [7, 3, 4, 2],
       [9, 6, 5, 8]])

In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
b = a[:2,:2]# rows,columns
b

array([[1, 2],
       [5, 6]])

In [21]:
b = a[:2,:2].copy()
b

array([[1, 2],
       [5, 6]])

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
b[0,0] = 77

In [25]:
b

array([[77,  2],
       [ 5,  6]])

In [26]:
a[0]

array([1, 2, 3, 4])

In [33]:
a[:,3]

array([ 4,  8, 12])

In [28]:
a > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [29]:
np.where(a>10, a*10,a)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 110, 120]])

In [30]:
np.where(a>10, 'agree','0') # otan isxyei h sinthiki a tote agree alliws 0

array([['0', '0', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '0', 'agree', 'agree']], dtype='<U5')

# TEST

In [36]:
start_time = time.time()
count = 1000000000
normalRange = range(count)
print(sum(normalRange))
print(f'Time taken {time.time() - start_time} seconds')

499999999500000000
Time taken 24.54898691177368 seconds


In [37]:
start_time = time.time()
count = 1000000000
nampyRange = np.arange(count)
print(nampyRange.sum())
print(f'Time taken {time.time() - start_time} seconds')

-1243309312
Time taken 1.689129114151001 seconds


In [41]:
start_time = time.time()
count = 1000000000
nampyRange = np.arange(count).astype('int64')
print(nampyRange.sum())
print(f'Time taken {time.time() - start_time} seconds')

499999999500000000
Time taken 42.957602739334106 seconds
